export const NOTIFICATION_TIMEOUT_SHORT = 3000
export const NOTIFICATION_TIMEOUT_LONG = 8000
export const ENQUEUE_NOTIFICATION = 'ENQUEUE_NOTIFICATION'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION'
