export const RECEIVE_INVOICES = 'RECEIVE_INVOICES'
export const UPDATE_INVOICE = 'UPDATE_INVOICE'

export const ADD_INVOICE = 'ADD_INVOICE'
export const ADD_INVOICE_SUCCESS = 'ADD_INVOICE_SUCCESS'
export const ADD_INVOICE_FAILURE = 'ADD_INVOICE_FAILURE'

export const CANCEL_INVOICE = 'CANCEL_INVOICE'
export const CANCEL_INVOICE_SUCCESS = 'CANCEL_INVOICE_SUCCESS'
export const CANCEL_INVOICE_FAILURE = 'CANCEL_INVOICE_FAILURE'

export const SETTLE_INVOICE = 'SETTLE_INVOICE'
export const SETTLE_INVOICE_SUCCESS = 'SETTLE_INVOICE_SUCCESS'
export const SETTLE_INVOICE_FAILURE = 'SETTLE_INVOICE_FAILURE'
export const CLEAR_SETTLE_INVOICE_ERROR = 'CLEAR_SETTLE_INVOICE_ERROR'
