commit_message: '[ci skip]'
files:
  - source: /app/translation/source/*.json
    translation: /app/translation/dest/%file_name%/%locale%.%file_extension%
    translate_attributes: '0'
    update_option: update_without_changes
