commit_message: '[ci skip]'
files:
  - source: /app/translations/en.json
    translation: /app/translations/%locale%.json
    languages_mapping:
      locale:
        af: af
        ar: ar
        bg: bg
        ca: ca
        zh-CN: zh-CN
        zh-TW: zh-TW
        hr: hr
        cs: cs
        da: da
        nl: nl
        en: en
        fi: fi
        fr: fr
        de: de
        el: el
        he: he
        hu: hu
        it: it
        ja: ja
        ko: ko
        no: no
        pl: pl
        pt-PT: pt-PT
        pt-BR: pt-BR
        ro: ro
        ru: ru
        sr: sr
        es: es
        sv: sv
        tr: tr
        uk: uk
        vi: vi
    update_option: update_without_changes
