commit_message: '[ci skip]'
files:
  - source: /app/locales/dev/*.json
    translation: /app/locales/%locale%/%original_file_name%
    translate_attributes: '0'
    update_option: update_without_changes
