commit_message: '[ci skip]'
files:
  - source: /app/translations/en.json
    translation: /app/translations/%locale%.json
    languages_mapping:
      locale:
        af-ZA: af
        ar-SA: ar
        bg-BG: bg
        ca-ES: ca
        cs-CZ: cs
        da-DK: da
        de-DE: de
        el-GR: el
        en-US: en
        es-ES: es
        fi-FI: fi
        fr-FR: fr
        he-IL: he
        hr-HR: hr
        hu-HU: hu
        it-IT: it
        ja-JP: ja
        ko-KR: ko
        nl-NL: nl
        no-NO: no
        pl-PL: pl
        pt-BR: pt-BR
        pt-PT: pt-PT
        ro-RO: ro
        ru-RU: ru
        sr-SP: sr
        sv-SE: sv
        tr-TR: tr
        uk-UA: uk
        vi-VN: vi
        zh-CN: zh-CN
        zh-TW: zh-TW
    update_option: update_without_changes
