builds:
  - id: lnd
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    binary: lnd
    main: ./cmd/lnd
    ldflags:
      - -s -w
      - -X github.com/lightningnetwork/lnd/build.Commit={{.Tag}}
      - -X github.com/lightningnetwork/lnd/build.RawTags=experimental,monitoring,autopilotrpc,chainrpc,invoicesrpc,signrpc,routerrpc,walletrpc,watchtowerrpc,wtclientrpc"
      - -X github.com/lightningnetwork/lnd/build.CommitHash={{.FullCommit}}
      - -X github.com/lightningnetwork/lnd/build.GoVersion={{.Env.GOVERSION}}
    flags:
      - -v
      - -trimpath
      - -tags=experimental monitoring autopilotrpc chainrpc invoicesrpc signrpc routerrpc walletrpc watchtowerrpc wtclientrpc

  - id: lncli
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    binary: lncli
    main: ./cmd/lncli
    ldflags:
      - -s -w
      - -X github.com/lightningnetwork/lnd/build.Commit={{.Tag}}
      - -X github.com/lightningnetwork/lnd/build.RawTags=experimental,monitoring,autopilotrpc,chainrpc,invoicesrpc,signrpc,routerrpc,walletrpc,watchtowerrpc,wtclientrpc"
      - -X github.com/lightningnetwork/lnd/build.CommitHash={{.FullCommit}}
      - -X github.com/lightningnetwork/lnd/build.GoVersion={{.Env.GOVERSION}}
    flags:
      - -v
      - -trimpath
      - -tags=experimental monitoring autopilotrpc chainrpc invoicesrpc signrpc routerrpc walletrpc watchtowerrpc wtclientrpc
archives:
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ .Arm }}-v{{ .Version }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*
    wrap_in_directory: true
checksum:
  name_template: 'manifest-{{ .Version }}.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
signs:
  - artifacts: checksum
release:
  github:
    owner: LN-Zap
    name: lnd
  prerelease: true
  name_template: '{{.ProjectName}} v{{.Version}}'
before:
  hooks:
    - make clean
    - go mod download
