import '@storybook/addon-options/register'
import '@storybook/addon-backgrounds/register'
import 'storybook-addon-styled-component-theme/dist/register'
import '@storybook/addon-storysource/register'
import '@storybook/addon-actions/register'
