export const SET_CHANNEL_VIEW_MODE = 'SET_CHANNEL_VIEW_MODE'
export const SET_SELECTED_CHANNEL = 'SET_SELECTED_CHANNEL'
export const CHANGE_CHANNEL_FILTER = 'CHANGE_CHANNEL_FILTER'
export const CHANGE_CHANNEL_SORT = 'CHANGE_CHANNEL_SORT'
export const CHANGE_CHANNEL_SORT_ORDER = 'CHANGE_CHANNEL_SORT_ORDER'
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY'
export const GET_CHANNELS = 'GET_CHANNELS'
export const RECEIVE_CHANNELS = 'RECEIVE_CHANNELS'
export const ADD_LOADING_PUBKEY = 'ADD_LOADING_PUBKEY'
export const REMOVE_LOADING_PUBKEY = 'REMOVE_LOADING_PUBKEY'
export const ADD_CLOSING_CHAN_ID = 'ADD_CLOSING_CHAN_ID'
export const REMOVE_CLOSING_CHAN_ID = 'REMOVE_CLOSING_CHAN_ID'
export const GET_SUGGESTED_NODES = 'GET_SUGGESTED_NODES'
export const RECEIVE_SUGGESTED_NODES_ERROR = 'RECEIVE_SUGGESTED_NODES_ERROR'
export const RECEIVE_SUGGESTED_NODES = 'RECEIVE_SUGGESTED_NODES'
export const CLOSE_CHANNEL_DIALOG_ID = 'CLOSE_CHANNEL_DIALOG_ID'
export const OPEN_CHANNEL = 'OPEN_CHANNEL'
export const OPEN_CHANNEL_SUCCESS = 'OPEN_CHANNEL_SUCCESS'
export const OPEN_CHANNEL_FAILURE = 'OPEN_CHANNEL_FAILURE'

export const DEFAULT_FILTER = new Set([
  'ACTIVE_CHANNELS',
  'NON_ACTIVE_CHANNELS',
  'OPEN_PENDING_CHANNELS',
  'CLOSING_PENDING_CHANNELS',
])

export const CHANNELS_SORT_OPEN_DATE = 'CHANNELS_SORT_OPEN_DATE'
export const CHANNELS_SORT_REMOTE_BALANCE = 'CHANNELS_SORT_REMOTE_BALANCE'
export const CHANNELS_SORT_LOCAL_BALANCE = 'CHANNELS_SORT_LOCAL_BALANCE'
export const CHANNELS_SORT_ACTIVITY = 'CHANNELS_SORT_ACTIVITY'
export const CHANNELS_SORT_NAME = 'CHANNELS_SORT_NAME'
export const CHANNELS_SORT_CAPACITY = 'CHANNELS_SORT_CAPACITY'
